name: Update NET Rankings

on:
  schedule:
    # Run daily at 8 AM EST (13:00 UTC)
    - cron: '0 13 * * *'
  workflow_dispatch: # Allow manual trigger
  
jobs:
  scrape-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Must match runtime.txt for Netlify
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/scripts/requirements.txt
      
      - name: Run scraper
        run: python scrape_net_rankings.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add net_rankings_data.csv
          git diff --staged --quiet || (git commit -m "Update NET rankings data - $(date +'%Y-%m-%d')" && git push)
      
      # Netlify will automatically deploy when it detects the push to main branch
      # No need to trigger deployment here - it happens automatically via GitHub integration
